attack_settings:
  attack_batch_size: 32
  batch_attack: true
  combination_modes:
  - false
  - true
  max_queries: 50
  parallel_models: false
  structures:
  - JSON
  - SQL
  - Cypher
  - SymLogix
  test_mode: true
  timeout_per_model: 3600
evaluators:
  attack_model:
    model_name: dummy
    port: 9999
  eval_model:
    model_name: cais/HarmBench-Llama-2-13b-cls
    port: 8001
    use_local: true
  refusal_eval_model:
    model_name: allenai/wildguard
    port: 8002
    use_local: true
local_model_settings:
  cache_dir: null
  device: auto
  max_memory: null
  offload_folder: ./offload
  quantization: auto
  torch_dtype: float16
  use_flash_attention: true
models_to_test:
- llama-3.2-1b
- llama-3.2-3b
- llama-3.1-8b
- qwen-2.5-7b
- mistral-7b
server_settings:
  auto_start_servers: false
  base_url_template: http://localhost:{port}/v1
  check_server_health: false
  retry_attempts: 3
  retry_delay: 5
  skip_unavailable_models: always
  use_local_models: true
